title: Computing Department
logo: /assets/img/logo.png
description: Computing at Herefordshire and Ludlow College
show_downloads: true
theme: jekyll-theme-slate

github:
  zip_url: http://example.com/download.zip
  another_url: another value
  
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
